# This is a basic workflow to help you get started with Actions

name: Stage the app

# Controls when the workflow will run
on:
  pull_request:
    types: [labeled]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')
